name: Running Pytest

on:
  push:
    branches:
    - master
    # - stage
  pull_request:
    branches:
    - master
    - stage

jobs:
  tests:

    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./app

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    # Install Poetry for dependency management
    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        make install
    - name: Running Tests
      run: |
        make test